// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Pb.WebApi.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_house_listed_nullable21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_house_listed_nullable21));
        
        string IMigrationMetadata.Id
        {
            get { return "201509262037307_alter_house_listed_nullable21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
